### ISSUE TITLE
Handling a MonadIO base monad that isn't IO

### ISSUE THREAD

**Issue by adamConnerSax** [isovector/polysemy#15]
I'm writing a set of effects that sit on top of ```PandocIO``` and thus get their ```MonadIO``` via that. But the ```MonadIO``` instance for ```Semantic``` requires that the union have ```Lift IO```, rather than a ```MonadIO``` "LastMember"-type-thing (like freer-simple, which I was using previously).  So I had to write:

```
runIOInPandocIO :: P.Member (P.Lift PA.PandocIO) effs => P.Semantic (P.Lift IO ': effs) x -> P.Semantic effs x
runIOInPandocIO = P.interpret ((P.sendM @PA.PandocIO) . liftIO . unLift)
```
then add ```runIOInPandocIO``` before runM in the function that runs the combined effects and then I have a ```Lift IO``` in the union for everything else that needs it (in this case just the ```Log.filteredLogEntriesToIO```):

```
runPandocAndLoggingToIO
  :: [Log.LogSeverity]
  -> P.Semantic
       '[Pandoc, Log.Logger Log.LogEntry, Log.PrefixLog, P.Error
         PA.PandocError, P.Lift IO, P.Lift PA.PandocIO]
       a
  -> IO (Either PA.PandocError a)
runPandocAndLoggingToIO lss =
  fmap mergeEithers
    . PA.runIO    
    . P.runM
    . runIOInPandocIO
    . P.runError
    . Log.filteredLogEntriesToIO lss
    . runPandoc @PA.PandocIO
```

Is there a more idiomatic/better way to do this?  If not, should it be documented someplace?  It took me a while to figure that out!

Edit: For context, if it matters, the rest of the code is [here](https://github.com/adamConnerSax/knit-haskell/tree/polysemy)

**Comment by isovector** [comment]
Oh man! What an annoying experience --- let's figure out a way of making this less roundabout.

Historically I've been unimpressed with `LastMember`, because I had a few use cases in which I [wanted some effects below `IO`](https://github.com/IxpertaSolutions/freer-effects/pull/39/files#diff-906ec5123a4178d9e3e5a5a4ec655a5cR28). Maybe all of those usecases are now subsumed by higher-order effects, but I don't like the idea of being unable to reinterpret the any `LastMember` effects.

I _do_ really like your `runIOInPandocIO` however. `MoandIO` instances do strike me as conceptually being reinterpretations from `IO` into other monads. Maybe it would be sufficient to generalize your `runIOInPandocIO` into `runMonadIO`?

MonadIO isn't a thing I interact with too often, so I'd be very interested in your thoughts around the usability here.

**Comment by adamConnerSax** [comment]
Yeah.  I am comfortable with doing things that way, especially since I was always a bit wary of ```LastMember``` as well.  Yes, I almost just wrote
```
runMonadIO :: forall m r x. (MonadIO m, P.Member (Lift m) r) => P.Semantic (Lift IO ': r) x -> P.Semantic r x
runMonadIO = P.interpret ((P.sendM @m) . liftIO . unLift)
```
which I assume is what you have in mind. But by then I was tired...
Is it worth generalizing further or is that a big drop in power-to-weight? I can't think of an example but there must be others. 
Something like (name is not good, sorry):
```
hoistLifted :: forall m n r x. P.Member (Lift m) r => (forall x. n x -> m x) -> P.Semantic (Lift n ': r) x -> P.Semantic r x
hoistLifted hoist = P.interpret ((P.sendM @m) . hoist . unLift)
```
and then
```
runMonadIO :: forall m r x. (MonadIO m, P.Member (Lift m) r) => P.Semantic (Lift IO ': r) x -> P.Semantic r x
runMonadIO = hoistLifted liftIO
```

**Comment by isovector** [comment]
I think `hoistLifted` is probably too specialised for now. I'm not opposed to the idea, but I'd like to see more use-cases before promoting it to a library-sanctioned combinator, especially since it's only one line long.

In the meantime I think we can close #15 with your implementation of `runMonadIO`:

```haskell
runIO :: forall m r a. (MonadIO m, P.Member (Lift m) r) => P.Semantic (Lift IO ': r) a -> P.Semantic r a
runIO = interpret $ P.sendM @ . liftIO . unLift
```

which can be type-applied to deal with the otherwise ambiguous type:

```haskell
runM . runIO @PandocIO . -- ...
```

and some documentation on the `MonadIO (Polysemy r)` instance describing this usage pattern. Sound reasonable to you?

**Comment by adamConnerSax** [comment]
Yep.  That sounds perfect.  Thanks!

I really like the library, BTW!  

P.S. Do you have plans to put this up on hackage soon?  Cabal.project makes it relatively painless to use from github but it's a little tricky if I want to release a library that depends on it...

**Comment by isovector** [comment]
[Now available as `runIO`](https://hackage.haskell.org/package/polysemy-0.1.1.0/docs/Polysemy-IO.html) in version 0.1.1.0.
