### ISSUE TITLE
Naming confusion

### ISSUE THREAD

**Issue by luntain** [isovector/polysemy#25]
Trying to understand the code and have a couple of questions about the names of the data types.

`Sem`, short for `Semantics`, seems anything but. To me, the data type represents a DSL program short of semantics, which are provided to it in the form of the function `(∀ x. Union r (Sem r) x -> m x)`. Perhaps a better name for it would be Free(r), Eff, Syntax, or Dsl. In the [talk](https://youtu.be/-dHFOjcK6pA?t=1657), it was named Freer.
 
What is the inspiration for the name: `Yo`?

For the `Union` data type, does union there pertains to the effect types?

**Comment by isovector** [comment]
Yeah, you're right about `Sem`, but the library is called `polysemy` and `Poly` seemed too overloaded. I'm not particularly keen to change it, but could be convinced for the right combination of terse, unique (no `Eff`, etc --- they come with bad baggage!), non-overloaded and accurate.

`Yo` felt a lot like `Coyoneda` to me when I wrote it; but also naming things is hard and I just chose something short and easy to type. I'd be open to changing this one, since it's internal.

`Union` corresponds to set union; if we have effects and actions `A (Aa, Aaa)` and `B (Bb)` then `Union '[A, B]` has the union of actions `Aa`, `Aaa` and `Bb`.
