### ISSUE TITLE
it sucks that you can't call callbacks

### ISSUE THREAD

**Issue by isovector** [isovector/polysemy#69]
Consider this:

```haskell
    wv     <- input
    h      <- bindT hook
    istate <- getInitialStateT

    void $ sendM $ after wv #keyPressEvent $ \kp -> do
      kv   <- get kp #keyval
      void $ lower .@ runNavigation $ h $ chr (fromIntegral kv) <$ istate
      pure False
```

even though `hook` returns a `Bool`, `h` returns an `f Bool`. But an `f Bool` is no good because I need a regular bool for the line below!

DANG DOES THIS EVER SUCK.

The problem is that we don't know which higher-order interpreters may have already run that have thrown off our chances for static evacuation of `f`. Ok, but the interpreters themselves know. What if we added a constructor to `Yo`:

```haskell
evacuate :: (forall x. f x -> Maybe x)
```

Effects like state could say "yeah no problem bruh." Effects like `NonDet` or `Error`, nope, no can do. But I'm reasonably sure the only `Yo`s you have to deal with are the ones that have already run above you, so as long as you keep your `Error`s low in the stack, it should be fine?

If `evacuate` is feasible, we can stick it into `Tactics` and then in some cases call the callback above. Is this a good idea? I don't know, it's 2am.

**Comment by isovector** [comment]
I guess `Error` can do it in the `Right` case. So that's dope. Maybe there should be another bit:

```haskell
data EvacuationState = Always | Sometimes | Never

evacuationState :: EvacuationState
```

so that if you're concerned you can check and see what's what. is this valuable I HAVE NO IDEA. Maybe it should be reified at the TYPE LEVEL :o :o :o

**Comment by isovector** [comment]
Ok, what if `r` instead of just having the effect row also kept track of static properties of the effect. It could be like this:

```haskell
newtype Row (status :: EvacuationSatus) = Row
  { effects :: [(* -> *) -> * -> *]
  }
```

then `runError` can change the evacuation status in `r`, and we can write interpreters like the motivating example which REQUIRE THE ABILITY TO EVACUATE

**Comment by isovector** [comment]
```haskell
runError :: Sem (Row (Error e ': r) status) a -> Sem (Row r 'Sometimes) (Either e a)
```

**Comment by isovector** [comment]
Most code doesn't give a shit, so maybe this could be packaged into `Sem` if it were a tysym:

```haskell
type Sem = forall status. SEM status
```

**Comment by isovector** [comment]
This way  `r` stays just the effect row

**Comment by isovector** [comment]
All of this seems very feasible! investigate tomorrow

**Comment by isovector** [comment]
@gelisam @boj what do you think?

**Comment by zarybnicky** [comment]
I'm all for, this would make possible the Reflex integration that I tried to do a month ago (to use your example, I needed both a `Bool` and an `f Bool`, which I can get simply by doing `x <$ s`).

**Comment by gelisam** [comment]
Slow down :)

So, first things first. I don't recognize which library you're trying to wrap, as hoogle doesn't return anything for `runNavigation`. And it looks like you've changed your API for `interpretH`, it's now `input` and `bindT` instead of `runT` and `bindT`. But I think I get the general idea.

To make sure I do, let me write down some code. Here is a standalone piece of code, adapted from the Teletype example from polysemy-0.2.1.0's README in which the action takes a callback. As a first step, let's do the easy case first, in which we don't inspect the `Bool` returned by the callback.

    {-# LANGUAGE DataKinds, FlexibleContexts, GADTs, LambdaCase, PolyKinds, RankNTypes, ScopedTypeVariables, TemplateHaskell, TypeApplications, TypeOperators, TypeFamilies #-}
    import Polysemy
    
    data OptionalTeletype m a where
      OptionallyWriteTTY :: m Bool -> String -> OptionalTeletype m Bool
    makeSem ''OptionalTeletype
    
    -- |
    -- >>> runM .@ runTeletypeIO $ optionallyWriteTTY (pure True) "hello"
    -- hello
    -- True
    runTeletypeIO :: forall r a. Member (Lift IO) r
                  => (forall x. Sem r x -> IO x)
                  -> Sem (OptionalTeletype ': r) a
                  -> Sem r a
    runTeletypeIO finish = interpretH $ \case
      OptionallyWriteTTY callback msg -> do
        callback' <- runT callback
    
        let runIt :: Sem (OptionalTeletype ': r) x -> IO x
            runIt = finish .@ runTeletypeIO
    
        sendM $ do
          b <- runIt callback'
          putStrLn msg
          pure b

I would like to use `when b (putStrLn msg)` instead of `putStrLn msg`, so that the message is only printed if the callback returns `True`. Unfortunately, `b`'s type is `f Bool`, not `Bool`.

But wait a minute! I'm surprised the code even works with `putStrLn msg`. I would have expected `m Bool` to be too restrictive, and for polysemy's types to encourage the user to change their effect signature so it uses `m (a, Bool)` instead. Let me explain.

[One of the things I like about polysemy](https://twitter.com/haskell_cat/status/1119334275445346304) is that it that the type of `bindT` encourages the user to change their effect signatures to use `a -> m b` instead of `m b`. This way, when this becomes `f a -> m (f b)`, the side-effects represented as an `f ()` from the other layers have a chance to reach the body of the callback, via the `f a`. I had incorrectly assumed that `m Bool` would have a similar problem, that an `m Bool` has no chance to return the `f ()` side-effects anywhere, whereas an `m (f a, Bool)` could. But I was wrong: `runT` turns `m Bool` into `m (f Bool)`, and so the `f ()` side-effects can safely be returned.

All right, let's go back to `when b (putStrLn msg)`. This time we'd have a much easier time if, as I had mistakenly expected, `runT` had forced us to use `m (a, Bool)`, and `runT` produced an `m (f a, Bool)`! We'd be able to use `when` on the `Bool`, and also to feed the `f a` to the next `f a -> m (f b)` function if any.

The problem, of course, is that the callback could use an error-throwing side-effect to get out of their obligation to produce a `Bool`. This is supported with the current `m (f Bool)` approach, because `f` could be something like `Maybe`, but this wouldn't work with my proposed `m (f a, Bool)` approach, because `runT` cannot manufacture a `Bool` out of thin air.

> But I'm reasonably sure the only `Yo`s you have to deal with are the ones that have already run above you, so as long as you keep your `Error`s low in the stack, it should be fine?

I don't understand how that would work. Whether the `Error` layer is above or below my `OptionalTeletype` layer, the user can still use `Error` effects inside the callback, and so something still has to manufacture a `Bool` out of thin air, no?

I think that some effects, like `Error` and `OptionalTeletype`, are fundamentally incompatible, and cannot appear in the same effect stack at all. Whereas another effect, which uses `m (Maybe Bool)`, might be compatible with `Error`. Or another interpreter for the same effect? I don't know, this is hard!

**Comment by isovector** [comment]
Okay, #71 has a draft implementation of the evacuation stuff. Everything typechecks, so apparently this is a safe thing to do!

**Comment by isovector** [comment]
Whether or not its _wise_ is a separate question!

**Comment by jkachmar** [comment]
@gelisam for an example of an effect that this pattern would enable (and which I believe would be pretty neat!) check out [this gist](https://gist.github.com/jkachmar/978ef20441c3fcac7ce7a0206bb88321#file-sisyphus-hs).

It’s implemented in terms of ‘fused-effects`, but I cannot define an `Effect` instance for it and therefore I cannot define it in `polysemy`.

Having a Monadic action that I can examine the result of and conditionally retry is super useful, IMO. An effect framework that admits this behavior would be pretty uniquely qualified to present some ergonomic APIs for a lot of stuff that’s not super fun to code around now.


e.g. An HTTP client library that with built-in support for retrying based on status code or response body state, but which could also be trivially stubbed out at multiple levels of abstraction because it’s implemented in terms of `polysemy` effects.

**Comment by isovector** [comment]
#73 is a better place to chat about this.
